services:
  rhino-pumps-app:
  # remove build: section
  # NAS should not be building the image, it should be pulling from Docker Hub
    build:
      context: . # build from repo on NAS
      dockerfile: Dockerfile
      # Use the following line to build from a remote GitHub repo instead of local files
      # image: ghcr.io/tadjemoore/ProjectManagement:latest
  
  container_name: rhino-pumps-app
  
  ports:
    - "8000:8000" # NAS port: Container port
  
  volumes:
    # Should data change to Projects.db? Or should it be a directory for multiple files?
    - /volume1/docker/rhino-pumps-app:/data # Persistent app data on the NAS
  
  restart: unless-stopped