services:
  rhino-projects-server:
  # remove build: section
  # NAS should not be building the image, it should be pulling from Docker Hub
    image: rhino-projects-server:latest
      # Use the following line to build from a remote GitHub repo instead of local files
      # image: ghcr.io/tadjemoore/ProjectManagement:latest
  
    container_name: rhino-projects-server
  
    ports:
      - "8000:8000" # NAS port: Container port
  
    volumes:
      # Should data change to Projects.db? Or should it be a directory for multiple files?
      - /volume1/docker/rhino-projects-server/data:/data # NAS path: Container path
      - /volume1/docker/rhino-projects-server/logs:/app/logs # NAS path: Container path
  
    restart: unless-stopped